export {default as Home} from './Home';
export {default as Profile} from './Profile';
export {default as ProfileEdit} from './ProfileEdit';
export {default as Achievement} from './Achievement';
export {default as TanyaJawab} from './TanyaJawab';
export {default as CariTeman} from './CariTeman';
export {default as Quiz} from './Quiz';
export {default as TEST } from './TEST';
export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as HomeDosen} from './HomeDosen';
export {default as Landing} from './Landing';
